import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const productDetails = [
  { name: 'Zero-Gravity Yo-Yo', description: 'It comes back up, but does it ever come down? Experience the thrill of uncertainty with every flick.', price: 1299, category: 'Toys' },
  { name: 'Invisible Dog Leash', description: 'Perfect for walks with your imaginary friend. Finally, a leash that understands the need for personal space.', price: 499, category: 'Pet Supplies' },
  { name: 'Dehydrated Water', description: 'Just add water! Each can contains enough powder to make up to one gallon of refreshing H2O. Caution: Do not consume powder directly.', price: 199, category: 'Kitchen' },
  { name: 'Instant Plant Seeds', description: 'Tired of waiting for nature? So are we. From seed to full-grown oak in under 30 seconds. Soil not included.', price: 2499, category: 'Garden' },
  { name: 'Portable Black Hole', description: 'Misplaced your keys? Annoying neighbor? Small existential dread? Make it all disappear with our patented pocket singularity.', price: 9999, category: 'Gadgets' },
  { name: 'Self-Solving Rubik\'s Cube', description: 'Impress your friends and question your own intelligence. It solves itself, but the real puzzle is how.', price: 3500, category: 'Toys' },
  { name: 'The Unlosable Sock Pair', description: 'The revolution in laundry technology. Each sock is quantum-entangled with its partner, ensuring they can never be separated. Or can they?', price: 1599, category: 'Apparel' },
  { name: 'Bottomless Snack Bag', description: 'A caloric paradox wrapped in a burlap sack. Reaches into the bag and pull out a different snack every time. Never repeats. Maybe.', price: 5000, category: 'Kitchen' },
  { name: 'Self-Typing Keyboard', description: 'Suffering from writer\'s block? This keyboard finishes your sentences, your emails, and maybe even your novel.', price: 7500, category: 'Productivity' },
  { name: 'The Inspiration Pen', description: 'This pen has been pre-loaded with the brainwaves of history\'s greatest thinkers. Just hold it and wait for genius to strike.', price: 2200, category: 'Productivity' },
  { name: 'Auto-Seasoning Salt Shaker', description: 'Leveraging advanced taste-bud-reading technology, it dispenses the perfect amount of seasoning every time.', price: 1800, category: 'Kitchen' },
  { name: 'Ever-Perfect Mug', description: 'Keeps your coffee piping hot and your iced tea perfectly chilled. Simultaneously. Don\'t ask how.', price: 2800, category: 'Kitchen' },
  { name: 'Mood-Ring T-Shirt', description: 'A shirt that changes color to reflect your emotional state. A great way to warn others... or attract attention.', price: 4200, category: 'Apparel' },
  { name: 'Perpetually Crisp Suit', description: 'Made from a memory-fabric that repels wrinkles and stains. Look sharp, even after sleeping in it.', price: 15000, category: 'Apparel' },
  { name: 'Universal Remote', description: 'Controls everything. Your TV, your smart home, your neighbor\'s garage door, the stock market. Use with caution.', price: 8000, category: 'Gadgets' },
  { name: 'Dream Recorder', description: 'Ever wanted to re-watch that dream where you could fly? Now you can. Side effects may include reality confusion.', price: 25000, category: 'Gadgets' },
  { name: 'PlayStation 5', description: 'Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, and an all-new generation of incredible games.', price: 49999, category: 'Electronics' },
  { name: 'PlayStation 5 Pro', description: 'The most powerful PlayStation yet. Experience 8K gaming, enhanced ray tracing, and performance that will redefine your reality.', price: 69999, category: 'Electronics' },
  { name: 'Xbox Series X', description: 'The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX ray tracing, a custom SSD, and 4K gaming.', price: 49999, category: 'Electronics' },
  { name: 'Xbox Series S', description: 'Go all-digital with the Xbox Series S and build a library of digital games. Your games, saves, and backups are safe in the cloud.', price: 29999, category: 'Electronics' },
  { name: 'Nintendo Switch', description: 'The Nintendo Switch system can be taken on the go so you have more time to play the games you love, however you like. At home, dock the system and play in HD.', price: 29999, category: 'Electronics' },
  { name: 'Nintendo Switch 2', description: 'The next evolution of hybrid gaming. Featuring a holographic screen, seamless cloud integration, and a library of games that read your mind.', price: 39999, category: 'Electronics' },
  { name: 'Quantum Smartphone', description: 'This isn\'t just a phone, it\'s a quantum leap. Features a self-healing screen, holographic calls, and a battery that lasts a lifetime.', price: 120000, category: 'Electronics' },
  { name: 'Holostream Projector', description: 'Turn any room into a holodeck. Projects interactive, high-definition 3D environments. Perfect for movies, gaming, or just escaping reality.', price: 45000, category: 'Electronics' },
  { name: 'EchoSphere Smart Speaker', description: 'It\'s not just listening, it\'s understanding. The EchoSphere anticipates your needs and subtly adjusts your environment for perfect comfort.', price: 9900, category: 'Electronics' },
  { name: 'CyberView VR Headset', description: 'Virtual reality that feels more real than reality itself. With a direct neural interface, you won\'t just see the game, you\'ll be in it.', price: 65000, category: 'Electronics' },
  { name: 'Nova Laptop', description: 'A feather-light laptop with heavyweight performance. Powered by a miniature star, its processing power is virtually limitless.', price: 250000, category: 'Electronics' },
  { name: 'Chrono Smartwatch', description: 'It doesn\'t just tell time, it manipulates it. Need an extra hour in your day? Just turn the dial. (Temporal side-effects not covered by warranty).', price: 18500, category: 'Electronics' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 21877, category: 'Home Goods' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 25199, category: 'Apparel' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 26649, category: 'Kitchen' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 27157, category: 'Gadgets' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 21868, category: 'Toys' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 16738, category: 'Pet Supplies' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 13594, category: 'Books' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 15306, category: 'Garden' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 2246, category: 'Productivity' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 13188, category: 'Sports & Outdoors' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 6220, category: 'Miscellaneous' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 10452, category: 'Home Goods' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 1969, category: 'Apparel' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 17469, category: 'Kitchen' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 1888, category: 'Gadgets' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 12260, category: 'Toys' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 2707, category: 'Pet Supplies' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 13915, category: 'Books' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 23680, category: 'Garden' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 13615, category: 'Productivity' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 17700, category: 'Sports & Outdoors' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 6690, category: 'Miscellaneous' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 17154, category: 'Home Goods' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 21919, category: 'Apparel' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 19129, category: 'Kitchen' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 24709, category: 'Gadgets' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 1686, category: 'Toys' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 26176, category: 'Pet Supplies' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 11116, category: 'Books' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 20117, category: 'Garden' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 17467, category: 'Productivity' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 22176, category: 'Sports & Outdoors' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 29094, category: 'Miscellaneous' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 28430, category: 'Home Goods' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 17799, category: 'Apparel' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 29994, category: 'Kitchen' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 13783, category: 'Gadgets' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 15383, category: 'Toys' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 27361, category: 'Pet Supplies' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 29285, category: 'Books' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 19808, category: 'Garden' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 15291, category: 'Productivity' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 29598, category: 'Sports & Outdoors' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 18196, category: 'Miscellaneous' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 26093, category: 'Home Goods' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 26421, category: 'Apparel' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 2793, category: 'Kitchen' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 13813, category: 'Gadgets' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 26369, category: 'Toys' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 1740, category: 'Pet Supplies' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 1572, category: 'Books' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 11065, category: 'Garden' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 19890, category: 'Productivity' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 23602, category: 'Sports & Outdoors' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 29707, category: 'Miscellaneous' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 14757, category: 'Home Goods' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 27072, category: 'Apparel' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 29424, category: 'Kitchen' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 23797, category: 'Gadgets' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 28415, category: 'Toys' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 2984, category: 'Pet Supplies' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 20117, category: 'Books' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 15383, category: 'Garden' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 12219, category: 'Productivity' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 22896, category: 'Sports & Outdoors' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 25164, category: 'Miscellaneous' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 28318, category: 'Home Goods' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 23512, category: 'Apparel' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 25345, category: 'Kitchen' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 24707, category: 'Gadgets' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 11066, category: 'Toys' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 20436, category: 'Pet Supplies' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 22449, category: 'Books' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 19572, category: 'Garden' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 11522, category: 'Productivity' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 14781, category: 'Sports & Outdoors' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 23415, category: 'Miscellaneous' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 26034, category: 'Home Goods' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 18451, category: 'Apparel' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 19688, category: 'Kitchen' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 13917, category: 'Gadgets' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 26362, category: 'Toys' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 2246, category: 'Pet Supplies' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 15469, category: 'Books' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 24785, category: 'Garden' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 1362, category: 'Productivity' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 13410, category: 'Sports & Outdoors' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 11186, category: 'Miscellaneous' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 10461, category: 'Home Goods' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 1394, category: 'Apparel' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 27958, category: 'Kitchen' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 1913, category: 'Gadgets' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 24458, category: 'Toys' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 1572, category: 'Pet Supplies' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 1993, category: 'Books' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 2420, category: 'Garden' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 15555, category: 'Productivity' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 17144, category: 'Sports & Outdoors' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 12921, category: 'Miscellaneous' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 24434, category: 'Home Goods' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 27488, category: 'Apparel' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 24874, category: 'Kitchen' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 20110, category: 'Gadgets' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 4627, category: 'Toys' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 13915, category: 'Pet Supplies' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 6220, category: 'Books' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 23604, category: 'Garden' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 28864, category: 'Productivity' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 26732, category: 'Sports & Outdoors' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 16568, category: 'Miscellaneous' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 28247, category: 'Home Goods' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 28230, category: 'Apparel' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 11091, category: 'Kitchen' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 6185, category: 'Gadgets' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 14713, category: 'Toys' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 2984, category: 'Pet Supplies' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 28414, category: 'Books' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 21394, category: 'Garden' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 22763, category: 'Productivity' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 20121, category: 'Sports & Outdoors' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 11520, category: 'Miscellaneous' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 12933, category: 'Home Goods' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 25417, category: 'Apparel' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 11986, category: 'Kitchen' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 24707, category: 'Gadgets' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 1391, category: 'Toys' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 22212, category: 'Pet Supplies' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 21252, category: 'Books' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 1228, category: 'Garden' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 20459, category: 'Productivity' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 13075, category: 'Sports & Outdoors' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 13733, category: 'Miscellaneous' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 2073, category: 'Home Goods' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 15309, category: 'Apparel' },
  { name: 'AI-powered Spatula', description: "A truly revolutionary ai-powered spatula that will change your life. Or at least mildly amuse you for a few minutes.", price: 29554, category: 'Kitchen' },
  { name: 'Recursive Button', description: "A truly revolutionary recursive button that will change your life. Or at least mildly amuse you for a few minutes.", price: 22170, category: 'Gadgets' },
  { name: 'Self-folding Picture Frame', description: "A truly revolutionary self-folding picture frame that will change your life. Or at least mildly amuse you for a few minutes.", price: 28833, category: 'Toys' },
  { name: 'Aromatic Water Bottle', description: "A truly revolutionary aromatic water bottle that will change your life. Or at least mildly amuse you for a few minutes.", price: 10452, category: 'Pet Supplies' },
  { name: 'Silent Backpack', description: "A truly revolutionary silent backpack that will change your life. Or at least mildly amuse you for a few minutes.", price: 29015, category: 'Books' },
  { name: 'Unbreakable Notebook', description: "A truly revolutionary unbreakable notebook that will change your life. Or at least mildly amuse you for a few minutes.", price: 26038, category: 'Garden' },
  { name: 'Quantum Toaster', description: "A truly revolutionary quantum toaster that will change your life. Or at least mildly amuse you for a few minutes.", price: 2056, category: 'Productivity' },
  { name: 'Singing Socks', description: "A truly revolutionary singing socks that will change your life. Or at least mildly amuse you for a few minutes.", price: 7713, category: 'Sports & Outdoors' },
  { name: 'Self-aware Lamp', description: "A truly revolutionary self-aware lamp that will change your life. Or at least mildly amuse you for a few minutes.", price: 16187, category: 'Miscellaneous' },
  { name: 'Gourmet Cheese Grater', description: "A truly revolutionary gourmet cheese grater that will change your life. Or at least mildly amuse you for a few minutes.", price: 20436, category: 'Home Goods' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A truly revolutionary hypoallergenic hamster wheel that will change your life. Or at least mildly amuse you for a few minutes.", price: 25164, category: 'Apparel' },
  { name: 'Anti-gravity Bookmark', description: "A truly revolutionary anti-gravity bookmark that will change your life. Or at least mildly amuse you for a few minutes.", price: 19800, category: 'Kitchen' },
  { name: 'Pocket-sized Shoelaces', description: "A truly revolutionary pocket-sized shoelaces that will change your life. Or at least mildly amuse you for a few minutes.", price: 20387, category: 'Gadgets' },
  { name: 'Sentient Potted Plant', description: "A truly revolutionary sentient potted plant that will change your life. Or at least mildly amuse you for a few minutes.", price: 27954, category: 'Toys' },
  { name: 'Holographic Umbrella', description: "A truly revolutionary holographic umbrella that will change your life. Or at least mildly amuse you for a few minutes.", price: 11130, category: 'Pet Supplies' },
  { name: 'Inflatable Doormat', description: "A truly revolutionary inflatable doormat that will change your life. Or at least mildly amuse you for a few minutes.", price: 1888, category: 'Books' },
  { name: 'Edible Spork', description: "A truly revolutionary edible spork that will change your life. Or at least mildly amuse you for a few minutes.", price: 2985, category: 'Garden' },
  { name: 'Time-traveling Rubber Chicken', description: "A truly revolutionary time-traveling rubber chicken that will change your life. Or at least mildly amuse you for a few minutes.", price: 11603, category: 'Productivity' },
  { name: 'Interdimensional Flux Capacitor', description: "A truly revolutionary interdimensional flux capacitor that will change your life. Or at least mildly amuse you for a few minutes.", price: 13615, category: 'Sports & Outdoors' },
  { name: 'Eco-friendly Pet Rock', description: "A truly revolutionary eco-friendly pet rock that will change your life. Or at least mildly amuse you for a few minutes.", price: 29891, category: 'Miscellaneous' },
];

export const products: Product[] = PlaceHolderImages.map((img, index) => ({
  id: img.id,
  name: productDetails[index]?.name || `Virtual Product ${index + 1}`,
  description: productDetails[index]?.description || 'An amazing virtual product.',
  price: productDetails[index]?.price || 1000,
  category: productDetails[index]?.category || 'Miscellaneous',
  imageUrl: img.imageUrl,
  imageHint: img.imageHint,
}));
