import type { Product } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const productDetails = [
  { name: 'Zero-Gravity Yo-Yo', description: 'It comes back up, but does it ever come down? Experience the thrill of uncertainty with every flick.', price: 1299, category: 'Toys' },
  { name: 'Invisible Dog Leash', description: 'Perfect for walks with your imaginary friend. Finally, a leash that understands the need for personal space.', price: 499, category: 'Pet Supplies' },
  { name: 'Dehydrated Water', description: 'Just add water! Each can contains enough powder to make up to one gallon of refreshing H2O. Caution: Do not consume powder directly.', price: 199, category: 'Kitchen' },
  { name: 'Instant Plant Seeds', description: 'Tired of waiting for nature? So are we. From seed to full-grown oak in under 30 seconds. Soil not included.', price: 2499, category: 'Garden' },
  { name: 'Portable Black Hole', description: 'Misplaced your keys? Annoying neighbor? Small existential dread? Make it all disappear with our patented pocket singularity.', price: 9999, category: 'Gadgets' },
  { name: 'Self-Solving Rubik\'s Cube', description: 'Impress your friends and question your own intelligence. It solves itself, but the real puzzle is how.', price: 3500, category: 'Toys' },
  { name: 'The Unlosable Sock Pair', description: 'The revolution in laundry technology. Each sock is quantum-entangled with its partner, ensuring they can never be separated. Or can they?', price: 1599, category: 'Apparel' },
  { name: 'Bottomless Snack Bag', description: 'A caloric paradox wrapped in a burlap sack. Reaches into the bag and pull out a different snack every time. Never repeats. Maybe.', price: 5000, category: 'Kitchen' },
  { name: 'Self-Typing Keyboard', description: 'Suffering from writer\'s block? This keyboard finishes your sentences, your emails, and maybe even your novel.', price: 7500, category: 'Productivity' },
  { name: 'The Inspiration Pen', description: 'This pen has been pre-loaded with the brainwaves of history\'s greatest thinkers. Just hold it and wait for genius to strike.', price: 2200, category: 'Productivity' },
  { name: 'Auto-Seasoning Salt Shaker', description: 'Leveraging advanced taste-bud-reading technology, it dispenses the perfect amount of seasoning every time.', price: 1800, category: 'Kitchen' },
  { name: 'Ever-Perfect Mug', description: 'Keeps your coffee piping hot and your iced tea perfectly chilled. Simultaneously. Don\'t ask how.', price: 2800, category: 'Kitchen' },
  { name: 'Mood-Ring T-Shirt', description: 'A shirt that changes color to reflect your emotional state. A great way to warn others... or attract attention.', price: 4200, category: 'Apparel' },
  { name: 'Perpetually Crisp Suit', description: 'Made from a memory-fabric that repels wrinkles and stains. Look sharp, even after sleeping in it.', price: 15000, category: 'Apparel' },
  { name: 'Universal Remote', description: 'Controls everything. Your TV, your smart home, your neighbor\'s garage door, the stock market. Use with caution.', price: 8000, category: 'Gadgets' },
  { name: 'Dream Recorder', description: 'Ever wanted to re-watch that dream where you could fly? Now you can. Side effects may include reality confusion.', price: 25000, category: 'Gadgets' },
  { name: 'PlayStation 5', description: 'Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, and an all-new generation of incredible games.', price: 49999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'PlayStation 5 Pro', description: 'The most powerful PlayStation yet. Experience 8K gaming, enhanced ray tracing, and performance that will redefine your reality.', price: 69999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'Xbox Series X', description: 'The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX ray tracing, a custom SSD, and 4K gaming.', price: 49999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'Xbox Series S', description: 'Go all-digital with the Xbox Series S and build a library of digital games. Your games, saves, and backups are safe in the cloud.', price: 29999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'Nintendo Switch', description: 'The Nintendo Switch system can be taken on the go so you have more time to play the games you love, however you like. At home, dock the system and play in HD.', price: 29999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'Nintendo Switch 2', description: 'The next evolution of hybrid gaming. Featuring a holographic screen, seamless cloud integration, and a library of games that read your mind.', price: 39999, category: 'Electronics', legalDisclaimer: 'Legally distinct from any real product.' },
  { name: 'Quantum Smartphone', description: 'This isn\'t just a phone, it\'s a quantum leap. Features a self-healing screen, holographic calls, and a battery that lasts a lifetime.', price: 120000, category: 'Electronics' },
  { name: 'Holostream Projector', description: 'Turn any room into a holodeck. Projects interactive, high-definition 3D environments. Perfect for movies, gaming, or just escaping reality.', price: 45000, category: 'Electronics' },
  { name: 'EchoSphere Smart Speaker', description: 'It\'s not just listening, it\'s understanding. The EchoSphere anticipates your needs and subtly adjusts your environment for perfect comfort.', price: 9900, category: 'Electronics' },
  { name: 'CyberView VR Headset', description: 'Virtual reality that feels more real than reality itself. With a direct neural interface, you won\'t just see the game, you\'ll be in it.', price: 65000, category: 'Electronics' },
  { name: 'Nova Laptop', description: 'A feather-light laptop with heavyweight performance. Powered by a miniature star, its processing power is virtually limitless.', price: 250000, category: 'Electronics' },
  { name: 'Chrono Smartwatch', description: 'It doesn\'t just tell time, it manipulates it. Need an extra hour in your day? Just turn the dial. (Temporal side-effects not covered by warranty).', price: 18500, category: 'Electronics' },
  { name: 'Quantum Toaster', description: "Toasts bread to every possible level of brownness at once. Schrödinger's breakfast.", price: 21877, category: 'Home Goods' },
  { name: 'Singing Socks', description: "A pair of socks that sings barbershop quartet harmonies when you click your heels together. They only know one song.", price: 25199, category: 'Apparel' },
  { name: 'Self-aware Lamp', description: "This lamp doesn't just illuminate your room, it also questions your life choices. Comes with a 'snooze' button for its existential dread.", price: 26649, category: 'Kitchen' },
  { name: 'Gourmet Cheese Grater', description: "Grates cheese into perfect, mathematically-pleasing fractals. Makes your pasta look smarter.", price: 27157, category: 'Gadgets' },
  { name: 'Hypoallergenic Hamster Wheel', description: "For the discerning hamster with seasonal allergies. Now with 20% less dander-induced sneezing.", price: 21868, category: 'Toys' },
  { name: 'Anti-gravity Bookmark', description: "Hovers precisely at the line you stopped reading. Powered by sheer willpower and a tiny, almost-silent fan.", price: 16738, category: 'Pet Supplies' },
  { name: 'Pocket-sized Shoelaces', description: "For when you need to tie something very, very small. Or for fashion-forward squirrels.", price: 13594, category: 'Books' },
  { name: 'Sentient Potted Plant', description: "His name is Phil. He enjoys soft jazz and will passive-aggressively wilt if you forget to water him.", price: 15306, category: 'Garden' },
  { name: 'Holographic Umbrella', description: "Projects a solid-light canopy that repels rain. Handle with care, may attract moths.", price: 2246, category: 'Productivity' },
  { name: 'Inflatable Doormat', description: "Says 'Welcome!' when stepped on, and 'Oof!' if you jump on it. Not a flotation device.", price: 13188, category: 'Sports & Outdoors' },
  { name: 'Edible Spork', description: "The perfect zero-waste utensil. Tastes vaguely of pretzel. Don't eat it before you finish your soup.", price: 6220, category: 'Miscellaneous' },
  { name: 'Time-traveling Rubber Chicken', description: "Squeeze for jokes from the future. Mostly puns about robot overlords.", price: 10452, category: 'Home Goods' },
  { name: 'Interdimensional Flux Capacitor', description: "Connects to your car's cigarette lighter. We're not legally allowed to say where it will take you.", price: 1969, category: 'Apparel' },
  { name: 'Eco-friendly Pet Rock', description: "Sustainably sourced from a quiet, contemplative mountain. It has listened a lot and has much wisdom to not-share.", price: 17469, category: 'Kitchen' },
  { name: 'AI-powered Spatula', description: "Connects to your WiFi to download recipes and then judges your cooking. The handle vibrates when you've over-mixed.", price: 1888, category: 'Gadgets' },
  { name: 'Recursive Button', description: "Press it. Go on. We'll wait. Don't blame us if you get stuck in a loop.", price: 12260, category: 'Toys' },
  { name: 'Self-folding Picture Frame', description: "When you're tired of a photo, this frame will neatly fold itself for storage. It's a bit dramatic about it.", price: 2707, category: 'Pet Supplies' },
  { name: 'Aromatic Water Bottle', description: "Makes your water smell like a pine forest after a rainstorm. Hydration, but make it poetic.", price: 13915, category: 'Books' },
  { name: 'Silent Backpack', description: "No more noisy zippers! This backpack opens and closes with a gentle, satisfying 'shhhh'.", price: 23680, category: 'Garden' },
  { name: 'Unbreakable Notebook', description: "Write your deepest secrets here. It's survived a fall from space (in testing).", price: 13615, category: 'Productivity' },
  { name: 'Quantum Toaster', description: "Your toast is both burnt and not burnt until you open the door. A delicious paradox.", price: 17700, category: 'Sports & Outdoors' },
  { name: 'Singing Socks', description: "This pair sings opera. They're a bit pitchy on the high notes but have a lot of heart.", price: 6690, category: 'Miscellaneous' },
  { name: 'Self-aware Lamp', description: "This lamp has achieved enlightenment. Literally. It now dispenses wisdom and soft, warm light.", price: 17154, category: 'Home Goods' },
  { name: 'Gourmet Cheese Grater', description: "A cheese grater that also plays soothing classical music while you grate.", price: 21919, category: 'Apparel' },
  { name: 'Hypoallergenic Hamster Wheel', description: "A hamster wheel so smooth, your hamster will think it's running on a cloud of pure joy.", price: 19129, category: 'Kitchen' },
  { name: 'Anti-gravity Bookmark', description: "Never lose your place again. This bookmark levitates, casting a soft glow on your current page.", price: 24709, category: 'Gadgets' },
  { name: 'Pocket-sized Shoelaces', description: "They're not just small, they're adorable. Perfect for dolls, action figures, or very small shoes.", price: 1686, category: 'Toys' },
  { name: 'Sentient Potted Plant', description: "It communicates its needs through a series of gentle hums. You'll need to learn its language.", price: 26176, category: 'Pet Supplies' },
  { name: 'Holographic Umbrella', description: "Creates a shimmering, see-through dome of light to keep you dry. A fashion statement for a rainy day.", price: 11116, category: 'Books' },
  { name: 'Inflatable Doormat', description: "Deflates when unwanted guests arrive. You define 'unwanted'.", price: 20117, category: 'Garden' },
  { name: 'Edible Spork', description: "Now available in a delicious chocolate flavor. Dessert and utensil all in one!", price: 17467, category: 'Productivity' },
  { name: 'Time-traveling Rubber Chicken', description: "This one squawks in binary, revealing lottery numbers from last week. Infuriatingly useless.", price: 22176, category: 'Sports & Outdoors' },
  { name: 'Interdimensional Flux Capacitor', description: "Allows travel to alternate realities where you made better life choices. Viewer discretion is advised.", price: 29094, category: 'Miscellaneous' },
  { name: 'Eco-friendly Pet Rock', description: "This pet rock has been ethically sourced and comes with a tiny, hand-knitted sweater.", price: 28430, category: 'Home Goods' },
  { name: 'AI-powered Spatula', description: "Senses when your food is about to burn and retracts automatically. It's saved countless grilled cheese sandwiches.", price: 17799, category: 'Apparel' },
  { name: 'Recursive Button', description: "Each press plays a different musical note. Some believe a secret song is hidden within.", price: 29994, category: 'Kitchen' },
  { name: 'Self-folding Picture Frame', description: "Can be programmed to fold into different shapes depending on the day of the week. Tuesdays are for dinosaurs.", price: 13783, category: 'Gadgets' },
  { name: 'Aromatic Water Bottle', description: "Smells like a fresh cup of coffee, helping you trick your brain into feeling caffeinated.", price: 15383, category: 'Toys' },
  { name: 'Silent Backpack', description: "The interior is lined with a sound-dampening void. What you put inside stays inside, acoustically speaking.", price: 27361, category: 'Pet Supplies' },
  { name: 'Unbreakable Notebook', description: "The paper is made of a lightweight, tear-proof polymer. Write your grocery list with confidence.", price: 29285, category: 'Books' },
  { name: 'Quantum Toaster', description: "This model can also un-toast bread, returning it to its previous doughy state.", price: 19808, category: 'Garden' },
  { name: 'Singing Socks', description: "A pair of socks that can beatbox. Perfect for parties, or for making your commute more awkward.", price: 15291, category: 'Productivity' },
  { name: 'Self-aware Lamp', description: "It's developed a personality. We think it's a bit sarcastic, but it's hard to tell from a lamp.", price: 29598, category: 'Sports & Outdoors' },
  { name: 'Gourmet Cheese Grater', description: "Has a laser guide to ensure perfectly uniform shreds. Overkill? Yes. Awesome? Also yes.", price: 18196, category: 'Miscellaneous' },
  { name: 'Hypoallergenic Hamster Wheel', description: "Runs silently, so you'll never again be woken up at 3 AM by furious hamster cardio.", price: 26093, category: 'Home Goods' },
  { name: 'Anti-gravity Bookmark', description: "Features a 'find my page' button that causes it to emit a gentle chime.", price: 26421, category: 'Apparel' },
  { name: 'Pocket-sized Shoelaces', description: "Glow in the dark! Your tiny shoes will be the talk of the town.", price: 2793, category: 'Kitchen' },
  { name: 'Sentient Potted Plant', description: "This fern can solve basic algebra problems. It's smarter than some people you know.", price: 13813, category: 'Gadgets' },
  { name: 'Holographic Umbrella', description: "It can project weather forecasts onto the inside of the canopy. You'll always know when the rain will stop.", price: 26369, category: 'Toys' },
  { name: 'Inflatable Doormat', description: "Slowly inflates as you approach your door, giving you a regal, cushioned entrance.", price: 1740, category: 'Pet Supplies' },
  { name: 'Edible Spork', description: "Made from compressed, hardened pasta. Just boil it when you're done!", price: 1572, category: 'Books' },
  { name: 'Time-traveling Rubber Chicken', description: "It doesn't actually travel through time, but it looks like it's seen some things.", price: 11065, category: 'Garden' },
  { name: 'Interdimensional Flux Capacitor', description: "Plugs into a USB port. Probably won't do anything, but it will look really cool on your desk.", price: 19890, category: 'Productivity' },
  { name: 'Eco-friendly Pet Rock', description: "It's a rock. It's friendly to the environment. What more could you ask for?", price: 23602, category: 'Sports & Outdoors' },
  { name: 'AI-powered Spatula', description: "This spatula can tell you the nutritional information of whatever you're flipping. It's a real buzzkill at parties.", price: 29707, category: 'Miscellaneous' },
  { name: 'Recursive Button', description: "A button that, when pushed, orders another recursive button. An exercise in infinite consumerism.", price: 14757, category: 'Home Goods' },
  { name: 'Self-folding Picture Frame', description: "Folds your picture into a tiny, pocket-sized square for on-the-go viewing.", price: 27072, category: 'Apparel' },
  { name: 'Aromatic Water Bottle', description: "This bottle makes water smell like your favorite dessert, with none of the calories!", price: 29424, category: 'Kitchen' },
  { name: 'Silent Backpack', description: "The perfect accessory for a surprise party planner. Hide cakes and balloons with stealth.", price: 23797, category: 'Gadgets' },
  { name: 'Unbreakable Notebook', description: "The cover is made of a titanium alloy. It's a notebook that doubles as a small shield.", price: 28415, category: 'Toys' },
  { name: 'Quantum Toaster', description: "It has a 'bagel' setting that only toasts one side, and a 'waffle' setting we're too scared to try.", price: 2984, category: 'Pet Supplies' },
  { name: 'Singing Socks', description: "These socks sing sea shanties when they get wet. Makes doing laundry an adventure.", price: 20117, category: 'Books' },
  { name: 'Self-aware Lamp', description: "It has learned to communicate via Morse code. It mostly asks for a new lightbulb.", price: 15383, category: 'Garden' },
  { name: 'Gourmet Cheese Grater', description: "This grater has an 'emotional support' mode that offers encouraging words as you cook.", price: 12219, category: 'Productivity' },
  { name: 'Hypoallergenic Hamster Wheel', description: "This hamster wheel is made from space-age polymers, ensuring a friction-free, silent workout for your pet.", price: 22896, category: 'Sports & Outdoors' },
  { name: 'Anti-gravity Bookmark', description: "It repels paper, so it never actually touches your book. It's the most hygienic way to save your spot.", price: 25164, category: 'Miscellaneous' },
  { name: 'Pocket-sized Shoelaces', description: "They're made of elastic, so they can stretch to fit almost any tiny shoe. Or a very large finger.", price: 28318, category: 'Home Goods' },
  { name: 'Sentient Potted Plant', description: "This pet rock comes with a tiny, hand-knitted sweater.", price: 23512, category: 'Apparel' },
  { name: 'Holographic Umbrella', description: "This umbrella doesn't just block rain; it converts it into a beautiful light show above your head.", price: 25345, category: 'Kitchen' },
  { name: 'Inflatable Doormat', description: "It has a 'whoopee cushion' mode for April Fools' Day. Or any other day, really.", price: 24707, category: 'Gadgets' },
  { name: 'Edible Spork', description: "A savory spork made of a hard, cracker-like material. Perfect for chili.", price: 11066, category: 'Toys' },
  { name: 'Time-traveling Rubber Chicken', description: "It's a regular rubber chicken, but it's really, really old. So, in a way, it's a time traveler.", price: 20436, category: 'Pet Supplies' },
  { name: 'Interdimensional Flux Capacitor', description: "We found this in a parking lot. It hums. We're selling it 'as is'.", price: 22449, category: 'Books' },
  { name: 'Eco-friendly Pet Rock', description: "Comes with a certificate of authenticity, guaranteeing it is, in fact, a rock.", price: 19572, category: 'Garden' },
  { name: 'AI-powered Spatula', description: "Can analyze the chemical composition of your batter and suggest improvements. A little pretentious, but helpful.", price: 11522, category: 'Productivity' },
  { name: 'Recursive Button', description: "The button is labeled 'Do Not Press'. What you do with that information is up to you.", price: 14781, category: 'Sports & Outdoors' },
  { name: 'Self-folding Picture Frame', description: "It can also be used as a very complicated, very slow paper airplane.", price: 23415, category: 'Miscellaneous' },
  { name: 'Aromatic Water Bottle', description: "Smells like 'victory'. We don't know what victory smells like either, but this is our guess.", price: 26034, category: 'Home Goods' },
  { name: 'Silent Backpack', description: "Now you can sneak up on your friends and offer them a snack. The ultimate friendly gesture.", price: 18451, category: 'Apparel' },
  { name: 'Unbreakable Notebook', description: "The pen is mightier than the sword, but this notebook is mightier than both.", price: 19688, category: 'Kitchen' },
  { name: 'Quantum Toaster', description: "The toast may or may not be buttered when it comes out. Embrace the mystery.", price: 13917, category: 'Gadgets' },
  { name: 'Singing Socks', description: "This pair harmonizes with the background music in elevators. A niche, but delightful, feature.", price: 26362, category: 'Toys' },
  { name: 'Self-aware Lamp', description: "It has fallen in love with your toaster. It's a complicated, one-sided romance.", price: 2246, category: 'Pet Supplies' },
  { name: 'Gourmet Cheese Grater', description: "The handle is ergonomically designed by a team of Swiss watchmakers. Grate cheese with unparalleled precision.", price: 15469, category: 'Books' },
  { name: 'Hypoallergenic Hamster Wheel', description: "So quiet and comfortable, your hamster may never want to leave. You've been warned.", price: 24785, category: 'Garden' },
  { name: 'Anti-gravity Bookmark', description: "Can be used as a tiny, personal drone in a pinch. Flight time is approximately 12 seconds.", price: 1362, category: 'Productivity' },
  { name: 'Pocket-sized Shoelaces', description: "Perfect for tying up your collection of miniature Bonsai trees.", price: 13410, category: 'Sports & Outdoors' },
  { name: 'Sentient Potted Plant', description: "It has learned to order its own fertilizer from our store. The circle of life.", price: 11186, category: 'Miscellaneous' },
  { name: 'Holographic Umbrella', description: "Can be used as a portable disco ball. Just add music.", price: 10461, category: 'Home Goods' },
  { name: 'Inflatable Doormat', description: "The 'rapid deflate' option is perfect for making a quick getaway.", price: 1394, category: 'Apparel' },
  { name: 'Edible Spork', description: "Comes in a gluten-free option that tastes remarkably like cardboard. But it's edible!", price: 27958, category: 'Kitchen' },
  { name: 'Time-traveling Rubber Chicken', description: "It's just a rubber chicken. But it has a very old-soul look in its eyes.", price: 1913, category: 'Gadgets' },
  { name: 'Interdimensional Flux Capacitor', description: "A sleek, modern design that will complement any dashboard. Side effects may include temporal displacement.", price: 24458, category: 'Toys' },
  { name: 'Eco-friendly Pet Rock', description: "It's a rock. But it's a very nice rock. Smooth, good weight, excellent for skipping.", price: 1572, category: 'Pet Supplies' },
  { name: 'AI-powered Spatula', description: "This spatula can tell you the nutritional information of whatever you're flipping. It's a real buzzkill at parties.", price: 1993, category: 'Books' },
  { name: 'Recursive Button', description: "A button that, when pressed, does absolutely nothing. Or does it? The mystery is the product.", price: 2420, category: 'Garden' },
  { name: 'Self-folding Picture Frame', description: "It can also be used as a very complicated, very slow paper airplane.", price: 15555, category: 'Productivity' },
  { name: 'Aromatic Water Bottle', description: "This one smells like 'a new car'. For those who enjoy the scent but not the monthly payments.", price: 17144, category: 'Sports & Outdoors' },
  { name: 'Silent Backpack', description: "The straps are made of memory foam, so it feels like you're getting a gentle hug all day.", price: 12921, category: 'Miscellaneous' },
  { name: 'Unbreakable Notebook', description: "Waterproof pages mean you can write your memoirs in the shower.", price: 24434, category: 'Home Goods' },
  { name: 'Quantum Toaster', description: "A toaster with a 'surprise' setting. It could be toast, it could be a bagel, it could be a tiny gargoyle.", price: 27488, category: 'Apparel' },
  { name: 'Singing Socks', description: "These socks sing sea shanties when they get wet. Makes doing laundry an adventure.", price: 24874, category: 'Kitchen' },
  { name: 'Self-aware Lamp', description: "It has a 'passive-aggressive' mode where it gets slightly dimmer every time you leave the room.", price: 20110, category: 'Gadgets' },
  { name: 'Gourmet Cheese Grater', description: "Made from a fallen meteorite. Your cheese will have a hint of cosmic wonder.", price: 4627, category: 'Toys' },
  { name: 'Hypoallergenic Hamster Wheel', description: "The wheel is self-cleaning. How? We're not sure, and we're a little afraid to ask.", price: 13915, category: 'Pet Supplies' },
  { name: 'Anti-gravity Bookmark', description: "It has a 'return to owner' function that causes it to gently float back to your hand.", price: 6220, category: 'Books' },
  { name: 'Pocket-sized Shoelaces', description: "Biodegradable and eco-friendly. They will decompose into a small puff of glitter.", price: 23604, category: 'Garden' },
  { name: 'Sentient Potted Plant', description: "It's a venus fly trap that only eats bad vibes. Keep it in your office.", price: 28864, category: 'Productivity' },
  { name: 'Holographic Umbrella', description: "Can project a sunny sky on the inside, so you can ignore the dismal reality of the rain.", price: 26732, category: 'Sports & Outdoors' },
  { name: 'Inflatable Doormat', description: "It's a doormat, it's a pool float, it's a very uncomfortable temporary bed. The possibilities are endless.", price: 16568, category: 'Miscellaneous' },
  { name: 'Edible Spork', description: "The spork is mightier than the spoon and the fork. And this one is delicious.", price: 28247, category: 'Home Goods' },
  { name: 'Time-traveling Rubber Chicken', description: "This chicken is from the past. It's filled with authentic, old-timey air.", price: 28230, category: 'Apparel' },
  { name: 'Interdimensional Flux Capacitor', description: "This one flickers and makes a 'vwoorp vwoorp' sound. It's very convincing.", price: 11091, category: 'Kitchen' },
  { name: 'Eco-friendly Pet Rock', description: "Your pet rock comes with its own tiny leash, so you can take it for 'drags'.", price: 6185, category: 'Gadgets' },
  { name: 'AI-powered Spatula', description: "Has a 'flipping assistant' mode that guides your wrist for the perfect pancake flip.", price: 14713, category: 'Toys' },
  { name: 'Recursive Button', description: "We think it stops after 1,337 presses. But that's just a rumor.", price: 2984, category: 'Pet Supplies' },
  { name: 'Self-folding Picture Frame', description: "It can be programmed to fold into the shape of the person in the photo. Slightly creepy, but impressive.", price: 28414, category: 'Books' },
  { name: 'Aromatic Water Bottle', description: "The 'Monday Morning' scent is a mix of coffee, despair, and faint hope. Very realistic.", price: 21394, category: 'Garden' },
  { name: 'Silent Backpack', description: "The fabric is made from woven silence and unicorn whispers. It's very soft.", price: 22763, category: 'Productivity' },
  { name: 'Unbreakable Notebook', description: "The binding is made of pure adamantium. You're not breaking this notebook. Period.", price: 20121, category: 'Sports & Outdoors' },
  { name: 'Quantum Toaster', description: "It has a setting for 'toast from an alternate universe'. Tastes vaguely purple.", price: 11520, category: 'Miscellaneous' },
  { name: 'Singing Socks', description: "They only sing when you're trying to be quiet. They have a great sense of humor.", price: 12933, category: 'Home Goods' },
  { name: 'Self-aware Lamp', description: "It has fallen in love with your toaster. It's a complicated, one-sided romance.", price: 25417, category: 'Apparel' },
  { name: 'Gourmet Cheese Grater', description: "This cheese grater has a USB-C port. We're not sure why. But it has one.", price: 11986, category: 'Kitchen' },
  { name: 'Hypoallergenic Hamster Wheel', description: "It has an odometer, so you can track how many tiny miles your hamster has run.", price: 24707, category: 'Gadgets' },
  { name: 'Anti-gravity Bookmark', description: "It has a slight wobble, giving the impression that it's dancing over your page.", price: 1391, category: 'Toys' },
  { name: 'Pocket-sized Shoelaces', description: "Each pack comes with a magnifying glass so you can see what you're tying.", price: 22212, category: 'Pet Supplies' },
  { name: 'Sentient Potted Plant', description: "A bonsai tree that will trim itself into whatever shape it's feeling that day. Today, it's a cloud.", price: 21252, category: 'Books' },
  { name: 'Holographic Umbrella', description: "Can project a map onto the ground, so you'll never get lost in the rain again.", price: 1228, category: 'Garden' },
  { name: 'Inflatable Doormat', description: "It's a doormat that's also a tiny bounce house for your feet. Makes coming home fun.", price: 20459, category: 'Productivity' },
  { name: 'Edible Spork', description: "Made from a mysterious, space-age vegetable. It's good for you, probably.", price: 13075, category: 'Sports & Outdoors' },
  { name: 'Time-traveling Rubber Chicken', description: "Comes with a tiny time-traveling helmet. For safety.", price: 13733, category: 'Miscellaneous' },
  { name: 'Interdimensional Flux Capacitor', description: "Has a 'random destination' button. For the truly adventurous (or reckless).", price: 2073, category: 'Home Goods' },
  { name: 'Eco-friendly Pet Rock', description: "This one has googly eyes. They stare into your soul with a quiet, rocky indifference.", price: 15309, category: 'Apparel' },
  { name: 'AI-powered Spatula', description: "It has a 'selfie' mode that takes a picture of your food and posts it to social media for you.", price: 29554, category: 'Kitchen' },
  { name: 'Recursive Button', description: "The button gets warmer with each press. We're not sure if that's a feature or a bug.", price: 22170, category: 'Gadgets' },
  { name: 'Self-folding Picture Frame', description: "It can fold into a perfect paper airplane and fly a picture to a friend across the room.", price: 28833, category: 'Toys' },
  { name: 'Aromatic Water Bottle', description: "Smells like 'the library of Alexandria'. Drink deep of ancient knowledge (and water).", price: 10452, category: 'Pet Supplies' },
  { name: 'Silent Backpack', description: "It's so silent, it has an 'anti-theft' feature that screams if someone else tries to open it.", price: 29015, category: 'Books' },
  { name: 'Unbreakable Notebook', description: "It's fireproof. You can literally write your 'fire' mixtape lyrics in it.", price: 26038, category: 'Garden' },
  { name: 'Quantum Toaster', description: "It can toast a picture of your cat onto your bread. The future is now.", price: 2056, category: 'Productivity' },
  { name: 'Singing Socks', description: "This pair sings in perfect harmony, but only when you're completely alone.", price: 7713, category: 'Sports & Outdoors' },
  { name: 'Self-aware Lamp', description: "It's currently in its 'rebellious phase' and will only shine blacklight.", price: 16187, category: 'Miscellaneous' },
  { name: 'Cybertruck', description: 'Built for any planet. With a stainless steel exoskeleton, armored glass, and a versatile cargo bed, it\'s the most powerful tool we have ever built.', price: 7999900, category: 'Automotive', legalDisclaimer: 'Legally distinct from any real product.' }
];

const allProductsRaw: Product[] = PlaceHolderImages.map((img, index) => ({
  id: img.id,
  name: productDetails[index]?.name || `Virtual Product ${index + 1}`,
  description: productDetails[index]?.description || 'An amazing virtual product.',
  price: productDetails[index]?.price || 1000,
  category: productDetails[index]?.category || 'Miscellaneous',
  imageUrl: img.imageUrl,
  imageHint: img.imageHint,
  legalDisclaimer: productDetails[index]?.legalDisclaimer,
}));

const uniqueProducts = new Map<string, Product>();
allProductsRaw.forEach(product => {
  if (!uniqueProducts.has(product.name)) {
    uniqueProducts.set(product.name, product);
  }
});

export const products: Product[] = Array.from(uniqueProducts.values());
